language: python
python:
  - "2.7"
  - "3.4"
addons:
  apt:
    packages:
      - gfortran
      - liblapack-dev
      - libatlas-dev
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
install:
  - conda create --yes -q -n pyenv mkl python=$TRAVIS_PYTHON_VERSION numpy=1.9.1 scipy=0.14.0 nose=1.3.7 six
  - source activate pyenv
  - pip install  coveralls
script:
  - nosetests -v --with-coverage --cover-package gridData --process-timeout=120 gridData
after_success:
  - coveralls
