env:
   global:
      - secure: "BQ6qt3AOkcapuzOAkct8LbpyF3MngFk/+v/HlSg9Cxfo1CrYZOuwzemLI+pXKTbJiJcUF2UbooaoQANk9uKc9/NZfBdWG8NRncV+c3QGceWJTU7NaDle04Gp1cmnH6a7YRWN652xaPa80vlM/hMtCLg9zSnk6HQXNlTcdrfzWus="
      - GH_DOC_BRANCH: master
      - GH_REPOSITORY: github.com/MDAnalysis/GridDataFormats.git
      - GIT_CI_USER: TravisCI
      - GIT_CI_EMAIL: TravisCI@mdanalysis.org
      - MDA_DOCDIR: build/sphinx/html
   matrix:
   - SETUP=full
   - SETUP=minimal
language: python
python:
  - "3.5"
  - "2.7"
sudo: false
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
install:
  - if [[ $SETUP == 'full' ]]; then conda create --yes -q -n pyenv python=$TRAVIS_PYTHON_VERSION numpy scipy nose sphinx; fi
  - if [[ $SETUP == 'minimal' ]]; then conda create --yes -q -n pyenv python=$TRAVIS_PYTHON_VERSION numpy nose sphinx; fi
  - source activate pyenv
  - pip install coveralls tempdir sphinx-sitemap
  - pip install -v ./
script:
  - nosetests -v --with-coverage --cover-package gridData --process-timeout=120 --processes=2 gridData
  - |
     test ${TRAVIS_PULL_REQUEST} == "false" && \
     test ${TRAVIS_BRANCH} == ${GH_DOC_BRANCH} && \
     test "${TRAVIS_BUILD_NUMBER}.1" == "${TRAVIS_JOB_NUMBER}" && \
     python setup.py build_sphinx || \
     true
after_success:
  - coveralls
  - |
     test ${TRAVIS_PULL_REQUEST} == "false" && \
     test ${TRAVIS_BRANCH} == ${GH_DOC_BRANCH} && \
     test "${TRAVIS_BUILD_NUMBER}.1" == "${TRAVIS_JOB_NUMBER}" && \
     bash ./ci/deploy_docs.sh
